import os
from os import system as cmd
import time
import random

#Example:
#1 loadingAniSlesh(0.5,0)
#2 loadingAniSlesh(0.5)
#3 loadingAniCube()
#Example 1: 0.5-DelayTime ; 0- status for "EndingsAni"(1-on;0-off)


def loadingAniCube(t=0.3,compl=1):
	cmd('cls')
	l=0
	l0=random.randint(1,10)
	l1=random.randint(11,28)
	l2=random.randint(29,45)
	l3=random.randint(46,57)
	l4=random.randint(58,74)
	l5=random.randint(75,84)
	l6=random.randint(85,94)
	l7=100
	#Animation
	print('                                                >                  <')
	print('                                                        ',l,'%      ')
	time.sleep(t)
	cmd('cls')
	print('                                                >█                 <')
	print('                                                        ',l0,'%     ')
	time.sleep(t)
	cmd('cls')
	print('                                                >███               <')
	print('                                                        ',l1,'%      ')
	time.sleep(t)
	cmd('cls')
	print('                                                >██████            <')
	print('                                                        ',l2,'%     ')
	time.sleep(t)
	cmd('cls')
	print('                                                >███████           <')
	print('                                                        ',l3,'%     ')
	time.sleep(t)
	cmd('cls')
	print('                                                >████████████      <')
	print('                                                        ',l4,'%      ')
	time.sleep(t)
	cmd('cls')
	print('                                                >██████████████    <')
	print('                                                        ',l5,'%     ')
	time.sleep(t)
	cmd('cls')
	print('                                                >█████████████████ <')
	print('                                                        ',l6,'%      ')
	time.sleep(t)
	cmd('cls')
	print('                                                >██████████████████<')
	print('                                                        ',l7,'%      ')
	time.sleep(0.4)
	#Endings animation
	if compl==1:	
		cmd('cls')
		print('                                                >██████████████████<')
		print('                                                      complete!    ')
		time.sleep(0.2)
		cmd('cls')
		print('                                                                    ')
		print('                                                                     ')
		time.sleep(0.2)
		cmd('cls')
		print('                                                >██████████████████<')
		print('                                                      complete!    ')
		time.sleep(0.2)
		cmd('cls')
		print('                                                                    ')
		print('                                                                     ')
		time.sleep(0.2)
		cmd('cls')
		print('                                                >██████████████████<')
		print('                                                      complete!    ')
		time.sleep(0.2)
		cmd('cls')
		print('                                                                    ')
		print('                                                                     ')
		time.sleep(0.2)
		cmd('cls')
		print('                                                >██████████████████<')
		print('                                                      complete!    ')
		time.sleep(1)
	else:
		pass

def loadingAniSlesh(t=0.3,compl=1):
	cmd('cls')
	l=0
	l0=random.randint(1,10)
	l1=random.randint(11,28)
	l2=random.randint(29,45)
	l3=random.randint(46,57)
	l4=random.randint(58,74)
	l5=random.randint(75,84)
	l6=random.randint(85,94)
	l7=100
	#Animation
	print('                                                [                  ]')
	print('                                                        ',l,'%      ')
	time.sleep(t)
	cmd('cls')
	print('                                                [/                 ]')
	print('                                                        ',l0,'%     ')
	time.sleep(t)
	cmd('cls')
	print('                                                [///               ]')
	print('                                                        ',l1,'%      ')
	time.sleep(t)
	cmd('cls')
	print('                                                [//////            ]')
	print('                                                        ',l2,'%     ')
	time.sleep(t)
	cmd('cls')
	print('                                                [///////           ]')
	print('                                                        ',l3,'%     ')
	time.sleep(t)
	cmd('cls')
	print('                                                [////////////      ]')
	print('                                                        ',l4,'%      ')
	time.sleep(t)
	cmd('cls')
	print('                                                [//////////////    ]')
	print('                                                        ',l5,'%     ')
	time.sleep(t)
	cmd('cls')
	print('                                                [///////////////// ]')
	print('                                                        ',l6,'%      ')
	time.sleep(t)
	cmd('cls')
	print('                                                [//////////////////]')
	print('                                                        ',l7,'%      ')
	time.sleep(0.4)
	#Endings animation
	if compl==1:	
		cmd('cls')
		print('                                                [//////////////////]')
		print('                                                      complete!    ')
		time.sleep(0.2)
		cmd('cls')
		print('                                                                    ')
		print('                                                                     ')
		time.sleep(0.2)
		cmd('cls')
		print('                                                [//////////////////]')
		print('                                                      complete!    ')
		time.sleep(0.2)
		cmd('cls')
		print('                                                                    ')
		print('                                                                     ')
		time.sleep(0.2)
		cmd('cls')
		print('                                                [//////////////////]')
		print('                                                      complete!    ')
		time.sleep(0.2)
		cmd('cls')
		print('                                                                    ')
		print('                                                                     ')
		time.sleep(0.2)
		cmd('cls')
		print('                                                [//////////////////]')
		print('                                                      complete!    ')
		time.sleep(1)
	else:
		pass