import os
from os import system as cmd
import time
import random

def AniCube(t=0.3,com=1):
	cmd('cls')
	l=0;l0=random.randint(1,10);l1=random.randint(11,28);l2=random.randint(29,45)
	l3=random.randint(46,57);l4=random.randint(58,74);l5=random.randint(75,84);l6=random.randint(85,94);l7=100
	print('                                                >                  <')
	print('                                                        ',l,'%      ')
	time.sleep(t)
	cmd('cls')
	print('                                                >█                 <')
	print('                                                        ',l0,'%     ')
	time.sleep(t+0.2)
	cmd('cls')
	print('                                                >███               <')
	print('                                                        ',l1,'%      ')
	time.sleep(t)
	cmd('cls')
	print('                                                >██████            <')
	print('                                                        ',l2,'%     ')
	time.sleep(t+0.3)
	cmd('cls')
	print('                                                >███████           <')
	print('                                                        ',l3,'%     ')
	time.sleep(t+0.8)
	cmd('cls')
	print('                                                >████████████      <')
	print('                                                        ',l4,'%      ')
	time.sleep(t+0.4)
	cmd('cls')
	print('                                                >██████████████    <')
	print('                                                        ',l5,'%     ')
	time.sleep(t-0.07)
	cmd('cls')
	print('                                                >█████████████████ <')
	print('                                                        ',l6,'%      ')
	time.sleep(t)
	cmd('cls')
	print('                                                >██████████████████<')
	print('                                                        ',l7,'%      ')
	time.sleep(0.4)
	if com==1:	
		cmd('cls')
		print('                                                >█████████████████<')
		print('                                                      complete!    ')
		time.sleep(0.2)
		cmd('cls')
		print('                                                                    ')
		print('                                                                     ')
		time.sleep(0.2)
		cmd('cls')
		print('                                                >██████████████████<')
		print('                                                      complete!    ')
		time.sleep(0.2)
		cmd('cls')
		print('                                                                    ')
		print('                                                                     ')
		time.sleep(0.2)
		cmd('cls')
		print('                                                >██████████████████<')
		print('                                                      complete!    ')
		time.sleep(0.2)
		cmd('cls')
		print('                                                                    ')
		print('                                                                     ')
		time.sleep(0.2)
		cmd('cls')
		print('                                                >██████████████████<')
		print('                                                      complete!    ')
		time.sleep(1)
	else:
		pass

def AniSlesh(t=0.3,com=1):
	cmd('cls')
	l=0;l0=random.randint(1,10);l1=random.randint(11,28);l2=random.randint(29,45)
	l3=random.randint(46,57);l4=random.randint(58,74);l5=random.randint(75,84);l6=random.randint(85,94);l7=100
	print('                                                [                  ]')
	print('                                                        ',l,'%      ')
	time.sleep(t)
	cmd('cls')
	print('                                                [/                 ]')
	print('                                                        ',l0,'%     ')
	time.sleep(t+0.2)
	cmd('cls')
	print('                                                [///               ]')
	print('                                                        ',l1,'%      ')
	time.sleep(t)
	cmd('cls')
	print('                                                [//////            ]')
	print('                                                        ',l2,'%     ')
	time.sleep(t+0.3)
	cmd('cls')
	print('                                                [///////           ]')
	print('                                                        ',l3,'%     ')
	time.sleep(t+0.8)
	cmd('cls')
	print('                                                [////////////      ]')
	print('                                                        ',l4,'%      ')
	time.sleep(t+0.4)
	cmd('cls')
	print('                                                [//////////////    ]')
	print('                                                        ',l5,'%     ')
	time.sleep(t-0.07)
	cmd('cls')
	print('                                                [///////////////// ]')
	print('                                                        ',l6,'%      ')
	time.sleep(t)
	cmd('cls')
	print('                                                [//////////////////]')
	print('                                                        ',l7,'%      ')
	time.sleep(0.4)
	if com==1:	
		cmd('cls')
		print('                                                [//////////////////]')
		print('                                                      complete!    ')
		time.sleep(0.2)
		cmd('cls')
		print('                                                                    ')
		print('                                                                     ')
		time.sleep(0.2)
		cmd('cls')
		print('                                                [//////////////////]')
		print('                                                      complete!    ')
		time.sleep(0.2)
		cmd('cls')
		print('                                                                    ')
		print('                                                                     ')
		time.sleep(0.2)
		cmd('cls')
		print('                                                [//////////////////]')
		print('                                                      complete!    ')
		time.sleep(0.2)
		cmd('cls')
		print('                                                                    ')
		print('                                                                     ')
		time.sleep(0.2)
		cmd('cls')
		print('                                                [//////////////////]')
		print('                                                      complete!    ')
		time.sleep(1)
	else:
		pass 